name: test_project
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  google_fonts: ^6.2.1
  mysql1: ^0.20.0
  window_manager: ^0.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/home_screen_images/
    - assets/images/
